language: go

go:
  - "1.13"

before_script:
  - GO111MODULE=off go get -u github.com/mitchellh/gox

script:
  - gox -arch="amd64" -os="windows linux darwin" -output="bin/{{.Dir}}-$TRAVIS_TAG-{{.OS}}_{{.Arch}}"
  - docker build -t rancher-service-update:latest .

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: bin/rancher-service-update*
    skip_cleanup: true
    overwrite: true
    name: "v$TRAVIS_TAG"
    on:
      tags: true

  - provider: script
    script: bash scripts/docker_push.sh
    skip_cleanup: true
    on:
      tags: true
